# You can update hooks to the latest versions with `pre-commit autoupdate`
repos:
  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
  # MyPy type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.16.1" 
    hooks:
      - id: mypy
  # Strip notebooks of output
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1 
    hooks:
      - id: nbstripout
  # Ensure uv.lock file is up to date
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.19
    hooks:
      - id: uv-lock
